'use strict'

const express = require('express')
const path = require('path')
const bodyParser = require('body-parser')
const session = require('express-session')
const cors = require('cors')
const cRole = require('./controllers/cRole')

const rUser = require('./routes/rUser')
const rLender = require('./routes/rLender')
const rCategory = require('./routes/rCategory')
const rSubcategory = require('./routes/rSubcategory')
const rEquipinfras = require('./routes/rEquipinfras')
const rVariety = require('./routes/rVariety')
const rCompany = require('./routes/rCompany')
const rLocation = require('./routes/rLocation')
const rPhone = require('./routes/rPhone')
const rRole = require('./routes/rRole')
const rVarietyDetail = require('./routes/rVarietyDetail')
const rCatalogue = require('./routes/rCatalogue')
const rPolicy = require('./routes/rPolicy')
const rResource = require('./routes/rResource')
const rActivity = require('./routes/rActivity')
const rComponent = require('./routes/rComponent')
const rServiceDetail = require('./routes/rServiceDetail')
const rCalendar = require('./routes/rCalendar')
const rRevision = require('./routes/rRevision')
const rServiceOrder = require('./routes/rServiceOrder')
const rSkill = require('./routes/rSkill')
const rQualification = require('./routes/rQualification')
const rBitacora = require('./routes/rBitacora')
const rMotive = require('./routes/rMotive')
const rGroup = require('./routes/rGroup')
const rParameter = require('./routes/rParameter')
const rPromotion = require('./routes/rPromotion')
const rNotificationDetail = require('./routes/rNotificationDetail')
const rNotification = require('./routes/rNotification')
const rReport = require('./routes/rReport')
const rQuestion = require('./routes/rQuestion')

// Initiate our app
const app = express()
// Configure our app
app.use(cors())
app.use(bodyParser.urlencoded({limit: "50mb", extended: true, parameterLimit:50000}))
app.use(bodyParser.json({limit: "50mb"}))
app.use('/public', express.static(path.join(__dirname, 'public')))
app.use(session({ secret: 'passport-tutorial', cookie: { maxAge: 60000 }, resave: false, saveUninitialized: false }))

app.use('/api/user', rUser)
app.use('/api/lender', rLender)
app.use('/api/category', rCategory)
app.use('/api/subcategory', rSubcategory)
app.use('/api/equipinfras', rEquipinfras)
app.use('/api/variety', rVariety)
app.use('/api/company', rCompany)
app.use('/api/location', rLocation)
app.use('/api/phone', rPhone)
app.use('/api/role', rRole)
app.use('/api/varietydetail', rVarietyDetail)
app.use('/api/catalogue', rCatalogue)
app.use('/api/policy', rPolicy)
app.use('/api/resource', rResource)
app.use('/api/activity', rActivity)
app.use('/api/component', rComponent)
app.use('/api/serviceDetail', rServiceDetail)
app.use('/api/calendar', rCalendar)
app.use('/api/revision', rRevision)
app.use('/api/serviceOrder', rServiceOrder)
app.use('/api/skill', rSkill)
app.get('/api/function', cRole.getFunctions)
app.use('/api/qualification', rQualification)
app.use('/api/bitacora', rBitacora)
app.use('/api/motive', rMotive)
app.use('/api/group', rGroup)
app.use('/api/parameter', rParameter)
app.use('/api/promotion', rPromotion)
app.use('/api/notification', rNotificationDetail)
app.use('/api/usernotification', rNotification)
app.use('/api/report', rReport)
app.use('/api/question', rQuestion)

module.exports = app
